const actionTypes = { 
    GET_HOME: 'GET_HOME',
    
    //music
    SET_CURRENT_SONG_ID: "SET_CURRENT_SONG_ID",
    SET_CURRENT_SONG_DATA: "SET_CURRENT_SONG_DATA",
    SET_CURRENT_ALBUM_ID: "SET_CURRENT_ALBUM_ID",
    SET_RECENT: "SET_RECENT",
    CLEAR_RECENT: "CLEAR_RECENT",
    PLAY: "PLAY",
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SET_FAVOURITE: 'SET_FAVOURITE',
    DEL_FAVOURITE_SONG: 'DEL_FAVOURITE_SONG',
    SEARCH: 'SEARCH'

}

export default actionTypes;